#if !defined(__DEFINES)
#define __DEFINES
#define OUT_VEND_DEV 0X40//64
#define IN_VEND_DEV 0XC0
#define OUT_VEND_INTF 0X41
#define IN_VEND_INTF 0XC1
#define OUT_VEND_EP 0X42
#define IN_VEND_EP 0XC2
//
#define FTDI_DEVICE_IN_REQTYPE (LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_RECIPIENT_DEVICE | LIBUSB_ENDPOINT_IN)
//
#define SET_BITMODE 0X0B
#define SETDATA 0X04
#define SETBAUD 0X03
#define SET_FLOW_CNTRL 0X02
#define SET_MODEM_CNTRL 0X01
#define READPINS 0X0C

#endif // __DEFINES
